name: LandClaim
main: net.minespire.landclaim.LandClaim
version: '${project.version}'
depend: [ Vault, WorldGuard, WorldEdit ]
api-version: 1.20
permissions:
  landclaim.world.*:
    description: Can claim in any world
    default: false
  landclaim.regions.*:
    description: Can claim infinite regions
    default: false
  landclaim.plots.*:
    description: Can claim infinite plots
    default: false
  landclaim.basic:
    description: Gives the standard players permissions
    default: false
    children:
      landclaim.gui: true
      landclaim.nearby: true
      landclaim.claimregion: true
      landclaim.claimplot: true
      landclaim.list: true
      landclaim.getworld: true
      landclaim.inspect.own: true
      landclaim.delete.own: true
      landclaim.vote: true
      landclaim.addplayer: true
      landclaim.removeplayer: true
      landclaim.flageditor: true
      landclaim.teleport: true
      landclaim.flag.basic: true
  landclaim.flag.basic:
    description: Give access to basic claim flags
    default: true
    children:
      landclaim.flag.build: true
      landclaim.flag.interact: true
      landclaim.flag.chest-access: true
      landclaim.flag.pvp: true
  landclaim.flag.all:
    description: Give access to all claim flags
    default: false
    children:
      landclaim.flag.build: true
      landclaim.flag.interact: true
      landclaim.flag.block-break: true
      landclaim.flag.block-place: true
      landclaim.flag.use: true
      landclaim.flag.damage-animals: true
      landclaim.flag.chest-access: true
      landclaim.flag.ride: true
      landclaim.flag.pvp: true
      landclaim.flag.sleep: true
      landclaim.flag.respawn-anchors: true
      landclaim.flag.tnt: true
      landclaim.flag.vehicle-place: true
      landclaim.flag.vehicle-destroy: true
      landclaim.flag.lighter: true
      landclaim.flag.block-trampling: true
      landclaim.flag.entry: true
      landclaim.flag.entry-deny-message: true
      landclaim.flag.greeting: true
      landclaim.flag.greeting-title: true
      landclaim.flag.farewell: true
      landclaim.flag.farewell-title: true
      landclaim.flag.enderpearl: true
      landclaim.flag.chorus-fruit-teleport: true
      landclaim.flag.item-pickup: true
      landclaim.flag.item-drop: true
      landclaim.flag.deny-message: true
  landclaim.admin:
    description: Give admin commands and abilities
    default: op
    children:
      landclaim.player: true
      landclaim.recountvotes: true
      landclaim.flag.all: true
      landclaim.edit.others: true
      landclaim.delete.others: true
      landclaim.inspect.others: true
      landclaim.reload: true
      landclaim.bypass: true
commands:
  lc:
    description: Base command for land claim
    usage: Type /lc claim <regionName> or /lc claimplot <plotName>